# Generated by Django 4.2.4 on 2023-10-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Lessons',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='lessons',
        ),
    ]
