# Generated by Django 4.2.4 on 2023-10-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_quiz_lessons_rename_quiz_question_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multianswer', to='app.question')),
            ],
        ),
    ]
