# Generated by Django 4.2.4 on 2023-10-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_multianswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer4',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
