# Generated by Django 4.2.4 on 2023-10-08 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_answer1_answer_answer_remove_answer_answer2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=225, unique=True)),
                ('lessons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsWM', to='app.lessons')),
            ],
        ),
        migrations.AlterField(
            model_name='multianswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multianswer', to='app.multiquestion'),
        ),
    ]
